name: 'Setup Environment'
description: 'Setup Node.js, pnpm, and install dependencies'


inputs:
  node-version:
    description: 'The Node.js version to use'
    required: true
    default: '20'
  pnpm-version:
    description: 'The pnpm version to use'
    required: true
    default: '8'


runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --ignore-scripts
      shell: bash

    - name: Install NX globally
      run: pnpm add -g nx
      shell: bash
