name: Main check

on:
  push:
    branches:
      - dev
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Run link check
        run: npx nx run-many --target=lint --all

      - name: Run building all libs
        run: nx run one-inch-community:build-all-libs

      - name: Run tests for all projects
        run: npx nx run-many --target=test --all
